name: Limit file size

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check size
      run: |
        $HOME/.local/bin/lizard | bash .github/workflows/lpar.sh 50